name: DeepExPo
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.12.31=h06a4308_0
  - cudatoolkit=11.8.0=h6a678d5_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.15=h5eee18b_0
  - python=3.10.16=he870216_1
  - readline=8.2=h5eee18b_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.44.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.1.0
      - accelerate==1.3.0
      - addict==2.4.0
      - aenum==3.1.15
      - aiofiles==22.1.0
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - aiosqlite==0.21.0
      - albucore==0.0.21
      - albumentations==1.4.23
      - alembic==1.14.1
      - altair==5.5.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==3.7.1
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.4
      - async-timeout==5.0.1
      - attrs==25.1.0
      - authlib==1.4.0
      - autotrain-advanced==0.8.36
      - babel==2.17.0
      - beautifulsoup4==4.13.0
      - bitsandbytes==0.45.0
      - bleach==6.2.0
      - blendmodes==2022
      - brotli==1.1.0
      - cachetools==5.5.1
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - chex==0.1.88
      - clean-fid==0.1.35
      - click==8.1.8
      - clip==1.0
      - clip-anytorch==2.6.0
      - cmake==3.31.4
      - colorlog==6.9.0
      - comm==0.2.2
      - contourpy==1.3.1
      - cryptography==44.0.0
      - cycler==0.12.1
      - cython==0.29.34
      - dadaptation==3.2
      - datasets==3.2.0
      - dctorch==0.1.2
      - debugpy==1.8.12
      - decorator==5.1.1
      - defusedxml==0.7.1
      - deprecation==2.1.0
      - dill==0.3.8
      - discord-webhook==1.3.0
      - diskcache==5.6.3
      - docker-pycreds==0.4.0
      - einops==0.8.0
      - entrypoints==0.4
      - etils==1.11.0
      - eval-type-backport==0.2.2
      - evaluate==0.4.3
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - facexlib==0.3.0
      - fastapi==0.115.6
      - fastjsonschema==2.21.1
      - ffmpy==0.5.0
      - filelock==3.17.0
      - filterpy==1.4.5
      - flax==0.10.2
      - fonttools==4.55.3
      - fqdn==1.5.1
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - ftfy==6.3.1
      - future==1.0.0
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-auth==2.38.0
      - google-auth-oauthlib==1.0.0
      - gradio==3.41.2
      - gradio-client==0.5.0
      - greenlet==3.1.1
      - grpcio==1.70.0
      - h11==0.14.0
      - hf-transfer==0.1.9
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.27.0
      - humanize==4.11.0
      - idna==3.10
      - imageio==2.36.1
      - importlib-metadata==8.6.1
      - importlib-resources==6.5.2
      - inflate64==1.0.1
      - inflection==0.5.1
      - invisible-watermark==0.2.0
      - ipadic==1.0.0
      - ipykernel==6.29.5
      - ipython==8.32.0
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jax==0.5.0
      - jaxlib==0.5.0
      - jedi==0.19.2
      - jinja2==3.1.5
      - jiwer==3.0.5
      - joblib==1.4.2
      - json5==0.10.0
      - jsonmerge==1.8.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter==1.1.1
      - jupyter-client==7.4.9
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-resource-usage==0.7.2
      - jupyter-server==1.24.0
      - jupyter-server-fileid==0.9.3
      - jupyter-server-terminals==0.5.3
      - jupyter-server-ydoc==0.8.0
      - jupyter-ydoc==0.2.5
      - jupyterlab==3.6.8
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-system-monitor==0.8.0
      - jupyterlab-topbar==0.6.1
      - jupyterlab-widgets==3.0.13
      - k-diffusion==0.2.0.dev0
      - kiwisolver==1.4.8
      - kornia==0.6.7
      - kornia-rs==0.1.8
      - lark==1.1.2
      - latent-diffusion==0.0.1
      - lazy-loader==0.4
      - lightning-utilities==0.12.0
      - lit==18.1.8
      - llvmlite==0.44.0
      - lmdb==1.6.2
      - loguru==0.7.3
      - lpips==0.1.4
      - mako==1.3.9
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.0
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mistune==3.1.1
      - ml-dtypes==0.5.1
      - mmsegmentation==1.2.2
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - multivolumefile==0.2.3
      - mypy-extensions==1.0.0
      - narwhals==1.24.1
      - nbclassic==1.2.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - nltk==3.9.1
      - notebook==6.5.7
      - notebook-shim==0.2.4
      - numba==0.61.0
      - numpy==1.26.2
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-ml-py==12.535.161
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu11==11.7.91
      - nvidia-nvtx-cu12==12.4.127
      - nvitop==1.3.2
      - oauthlib==3.2.2
      - omegaconf==2.2.3
      - open-clip-torch==2.20.0
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.11.0.86
      - opt-einsum==3.4.0
      - optax==0.2.4
      - optuna==4.1.0
      - orbax-checkpoint==0.11.2
      - orjson==3.10.15
      - overrides==7.7.0
      - packaging==24.2
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - parso==0.8.4
      - peft==0.14.0
      - pexpect==4.9.0
      - piexif==1.1.3
      - pillow==11.0.0
      - pillow-avif-plugin==1.4.3
      - pip==25.0
      - platformdirs==4.3.6
      - prettytable==3.12.0
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.50
      - propcache==0.2.1
      - protobuf==5.29.3
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py7zr==0.22.0
      - pyarrow==19.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pybcj==1.0.3
      - pycocotools==2.0.8
      - pycparser==2.22
      - pycryptodomex==3.21.0
      - pydantic==2.10.4
      - pydantic-core==2.27.2
      - pydub==0.25.1
      - pygments==2.19.1
      - pyngrok==7.2.1
      - pyparsing==3.2.1
      - pyppmd==1.1.1
      - pyre-extensions==0.0.29
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-json-logger==3.2.1
      - python-multipart==0.0.20
      - pytorch-lightning==1.9.4
      - pytorch-optimizer==2.12.0
      - pytz==2025.1
      - pywavelets==1.8.0
      - pyyaml==6.0.2
      - pyzmq==26.2.1
      - pyzstd==0.16.2
      - rapidfuzz==3.12.1
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - resize-right==0.0.2
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.9.4
      - rouge-score==0.1.2
      - rpds-py==0.22.3
      - rsa==4.9
      - ruff==0.9.4
      - sacremoses==0.1.1
      - safehttpx==0.1.6
      - safetensors==0.5.2
      - scikit-image==0.21.0
      - scikit-learn==1.6.0
      - scipy==1.15.0
      - semantic-version==2.10.0
      - send2trash==1.8.3
      - sentence-transformers==3.3.1
      - sentencepiece==0.2.0
      - sentry-sdk==2.20.0
      - seqeval==1.2.2
      - setproctitle==1.3.4
      - setuptools==75.8.0
      - shellingham==1.5.4
      - simplejson==3.19.3
      - simsimd==6.2.1
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.6
      - spandrel==0.3.4
      - spandrel-extra-arches==0.1.1
      - sqlalchemy==2.0.37
      - stack-data==0.6.3
      - starlette==0.41.3
      - stringzilla==3.11.3
      - sympy==1.13.1
      - tb-nightly==2.19.0a20250202
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tensorstore==0.1.71
      - termcolor==2.5.0
      - terminado==0.18.1
      - texttable==1.7.0
      - threadpoolctl==3.5.0
      - tifffile==2024.12.12
      - tiktoken==0.8.0
      - timm==1.0.12
      - tinycss2==1.4.0
      - tokenizers==0.21.0
      - tomesd==0.1.3
      - tomli==2.2.1
      - tomlkit==0.13.2
      - toolz==1.0.0
      - torch==2.1.2+cu118
      - torchaudio==2.1.2+cu118
      - torchdiffeq==0.2.3
      - torchmetrics==1.6.0
      - torchsde==0.2.6
      - torchvision==0.16.2+cu118
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - trampoline==0.1.2
      - transformers==4.48.0
      - triton==2.1.0
      - trl==0.13.0
      - typer==0.15.1
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.12.2
      - typing-inspect==0.9.0
      - tzdata==2025.1
      - uri-template==1.3.0
      - urllib3==2.3.0
      - uvicorn==0.34.0
      - wandb==0.18.7
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==11.0.3
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.13
      - xformers==0.0.23.post1+cu118
      - xgboost==2.1.3
      - xxhash==3.5.0
      - y-py==0.6.2
      - yapf==0.43.0
      - yarl==1.18.3
      - ypy-websocket==0.8.4
      - zipp==3.21.0
prefix: /home/xpzhao/anaconda3/envs/ProxyCLIP_huggingFace
